image: Visual Studio 2019
version: 1.0.{build}
configuration: Release

skip_commits:
  files:
    - 'Images/*'
    - 'README.md'

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.DirectX-Samples" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

environment:
  GITHUB_TOKEN:
    secure: awbDbCVBldNyz+7VzGnSLlBnczS0NtXrUaS7UkrwoOoUIAzE70QHYfKQuTyOJavb

nuget:
  disable_publish_on_pr: true

before_build:
  - for /R %%F in (*.sln) do nuget restore "%%F" -Verbosity quiet

build_script:
  - echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - for /R %%F in (*.sln) do msbuild /verbosity:minimal "%%F"

after_build:
  - DirectXRenderTargetScreenshot\DirectXRenderTargetScreenshot\bin\Release\netcoreapp3.1\DirectXRenderTargetScreenshot.exe

after_test:
- if "%DEPLOY%" == "True" git checkout -q master
- if "%DEPLOY%" == "True" git config core.safecrlf false
- if "%DEPLOY%" == "True" git config push.default simple
- if "%DEPLOY%" == "True" git config user.name \"Jérémy Ansel\""
- if "%DEPLOY%" == "True" git config user.email JeremyAnsel@users.noreply.github.com
- if "%DEPLOY%" == "True" git add -v --all Images
- if "%DEPLOY%" == "True" git add -v README.md
- if "%DEPLOY%" == "True" git commit -m "Update screenshots generated by CI"
- if "%DEPLOY%" == "True" git branch
- if "%DEPLOY%" == "True" git push -q https://%GITHUB_TOKEN%@github.com/JeremyAnsel/JeremyAnsel.DirectX-Samples.git
